version : '3'
 
services:
  clientapi:
    image: client-api-pipeline
    ports:
      - 9001:8080
    depends_on:
      - client-api-db-pipeline
  
  client-api-db-pipeline:
    image: client-api-db-pipeline
    ports:
      - 3306
